//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.WebUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int ID { get; set; }
        public int ShopID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Number { get; set; }
        public bool IsInDopingo { get; set; }
        public double TotalPrice { get; set; }
        public int OrderStatusID { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int CustomerID { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Shops Shops { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual OrderStatuses OrderStatuses { get; set; }
    }
}
