//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementSystem.WebUI.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductGallery = new HashSet<ProductGallery>();
            this.ProductCategories = new HashSet<ProductCategories>();
        }
    
        public int ID { get; set; }
        public int ShopID { get; set; }
        public string Name { get; set; }
        public string ProductCode { get; set; }
        public decimal Price { get; set; }
        public int TaxDescriptionID { get; set; }
        public int Number { get; set; }
        public string Description { get; set; }
        public string StockHoldingUnit { get; set; }
        public int OutOfStockStatusID { get; set; }
        public bool IsInStock { get; set; }
        public int WarrantyPeriodID { get; set; }
        public string ImagePath { get; set; }
        public string ThumbNailImagePath { get; set; }
        public bool IsInDopingo { get; set; }
        public string FileName { get; set; }
    
        public virtual OutOfStockStatuses OutOfStockStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGallery> ProductGallery { get; set; }
        public virtual Shops Shops { get; set; }
        public virtual TaxDescriptions TaxDescriptions { get; set; }
        public virtual WarrantyPeriods WarrantyPeriods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductCategories> ProductCategories { get; set; }
    }
}
